version: '3.1'

# service 定义容器列表
services :
  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"

  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

  
  consignment-service:
    build: ./consignment-service
    ports:
      - 8010:8010
    environment:
      MICRO_ADRESS: ":8010"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
      DISABLE_AUTH: "false"
    depends_on: 
      - datastore
  
  vessel-service:
    build: ./vessel-service
    ports: 
      - 8011:8010
    environment:
      MICRO_ADRESS: ":8010"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "datastore:27017"
    depends_on: 
      - datastore

  user-service:
    build: ./user-service
    ports:
    - 8013:8010
    environment:
      MICRO_ADDRESS: ":8010"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "000"
    depends_on:
      - database

  email-service:
    build: ./email-service
    ports:
    - 8015:8010
    environment:
      MICRO_ADDRESS: ":8010"
      MICRO_REGISTRY: "mdns"

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres:9.5.4
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: '000'
