// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vessel-service/proto/vessel/vessel.proto

package vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_986c3e1f103d74ba, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_986c3e1f103d74ba, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Specification struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight,proto3" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_986c3e1f103d74ba, []int{2}
}

func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (m *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(m, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Response struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	Created              bool      `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_986c3e1f103d74ba, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func init() {
	proto.RegisterType((*Vessel)(nil), "vessel.Vessel")
	proto.RegisterType((*Request)(nil), "vessel.Request")
	proto.RegisterType((*Specification)(nil), "vessel.Specification")
	proto.RegisterType((*Response)(nil), "vessel.Response")
}

func init() {
	proto.RegisterFile("vessel-service/proto/vessel/vessel.proto", fileDescriptor_986c3e1f103d74ba)
}

var fileDescriptor_986c3e1f103d74ba = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x69, 0x9b, 0x8f, 0x91, 0x16, 0x19, 0x11, 0xd6, 0xa2, 0x10, 0x72, 0x90, 0x1c, 0xb4,
	0x85, 0xfa, 0x07, 0x14, 0x41, 0xd0, 0xe3, 0x16, 0xf4, 0x58, 0xb6, 0xc9, 0xa8, 0x0b, 0xcd, 0x87,
	0xd9, 0x98, 0xd6, 0x93, 0x7f, 0xc5, 0x9f, 0x2a, 0x4c, 0x12, 0xa5, 0xa5, 0x78, 0xda, 0x79, 0x6f,
	0x66, 0x1f, 0x6f, 0xdf, 0x2c, 0x44, 0x35, 0x19, 0x43, 0xab, 0x2b, 0x43, 0x65, 0xad, 0x63, 0x9a,
	0x16, 0x65, 0x5e, 0xe5, 0xd3, 0x86, 0x6c, 0x8f, 0x09, 0x73, 0xe8, 0x34, 0x28, 0xfc, 0xb6, 0xc0,
	0x79, 0xe2, 0x12, 0x47, 0x60, 0xeb, 0x44, 0x58, 0x81, 0x15, 0xf9, 0xd2, 0xd6, 0x09, 0x8e, 0xc1,
	0x8b, 0x55, 0xa1, 0x62, 0x5d, 0x7d, 0x0a, 0x3b, 0xb0, 0xa2, 0x81, 0xfc, 0xc5, 0x78, 0x0e, 0x90,
	0xaa, 0xcd, 0x62, 0x4d, 0xfa, 0xf5, 0xad, 0x12, 0x3d, 0xee, 0xfa, 0xa9, 0xda, 0x3c, 0x33, 0x81,
	0x08, 0xfd, 0x4c, 0xa5, 0x24, 0xfa, 0x2c, 0xc6, 0x35, 0x9e, 0x81, 0xaf, 0x6a, 0xa5, 0x57, 0x6a,
	0xb9, 0x22, 0x31, 0x08, 0xac, 0xc8, 0x93, 0x7f, 0x04, 0x9e, 0x82, 0x97, 0xaf, 0x33, 0x2a, 0x17,
	0x3a, 0x11, 0x0e, 0xdf, 0x72, 0x19, 0x3f, 0x24, 0xa1, 0x0f, 0xae, 0xa4, 0xf7, 0x0f, 0x32, 0x55,
	0xf8, 0x08, 0xc3, 0x79, 0x41, 0xb1, 0x7e, 0xd1, 0xb1, 0xaa, 0x74, 0x9e, 0x6d, 0x79, 0xb4, 0xfe,
	0xf5, 0x68, 0xef, 0x78, 0x0c, 0x6b, 0xf0, 0x24, 0x99, 0x22, 0xcf, 0x0c, 0xe1, 0x05, 0xb4, 0x79,
	0xb0, 0xc8, 0xe1, 0x6c, 0x34, 0x69, 0xc3, 0x6a, 0xa2, 0x91, 0x6d, 0x17, 0x23, 0x70, 0x9b, 0xca,
	0x08, 0x3b, 0xe8, 0xed, 0x19, 0xec, 0xda, 0x28, 0xc0, 0x8d, 0x4b, 0x52, 0x15, 0x25, 0x9c, 0x8e,
	0x27, 0x3b, 0x38, 0xfb, 0x82, 0x61, 0x33, 0x3c, 0x6f, 0x96, 0x84, 0x37, 0x70, 0x7c, 0xaf, 0xb3,
	0xe4, 0xb6, 0xcb, 0xa2, 0x5d, 0xc7, 0x49, 0x27, 0xbd, 0xf5, 0xe2, 0xf1, 0x51, 0x47, 0x77, 0xe6,
	0xc3, 0x03, 0xbc, 0x04, 0xe7, 0x8e, 0xd5, 0x71, 0xc7, 0xcf, 0xbe, 0xe9, 0xa5, 0xc3, 0x3f, 0xe0,
	0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0x81, 0x1f, 0xfe, 0x3f, 0x2d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	FindAvailableVessel(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error)
	Create(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Response, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) FindAvailableVessel(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailableVessel", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) Create(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	FindAvailableVessel(context.Context, *Specification, *Response) error
	Create(context.Context, *Vessel, *Response) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) FindAvailableVessel(ctx context.Context, in *Specification, out *Response) error {
	return h.VesselServiceHandler.FindAvailableVessel(ctx, in, out)
}

func (h *VesselService) Create(ctx context.Context, in *Vessel, out *Response) error {
	return h.VesselServiceHandler.Create(ctx, in, out)
}
